// This file was auto-generated by Fern from our API Definition.

export interface Error_ {
    /** Human-readable error message */
    message: string;
    /** Additional error context */
    details?: Record<string, unknown>;
}
