// This file was auto-generated by Fern from our API Definition.

export interface Project {
    /** Unique identifier for the project */
    id: string;
    /** Name of the project */
    name: string;
    /** A brief description of the project */
    description?: string;
    /** When the project was created */
    created_at: string;
}
