// This file was auto-generated by Fern from our API Definition.

import type * as Taskboard from "../index.js";

export interface TaskList {
    data: Taskboard.Task[];
    /** Total number of tasks matching the query */
    total: number;
    limit?: number;
    offset?: number;
}
