// This file was auto-generated by Fern from our API Definition.

/** The current status of a task */
export const TaskStatus = {
    Backlog: "backlog",
    Todo: "todo",
    InProgress: "in_progress",
    Done: "done",
    Cancelled: "cancelled",
} as const;
export type TaskStatus = (typeof TaskStatus)[keyof typeof TaskStatus];
