// This file was auto-generated by Fern from our API Definition.

/** The priority level of a task */
export const TaskPriority = {
    Low: "low",
    Medium: "medium",
    High: "high",
    Urgent: "urgent",
} as const;
export type TaskPriority = (typeof TaskPriority)[keyof typeof TaskPriority];
