// This file was auto-generated by Fern from our API Definition.

import type * as Taskboard from "../index.js";

export interface Task {
    /** Unique identifier for the task */
    id: string;
    /** Short summary of the task */
    title: string;
    /** Detailed description of the task */
    description?: string;
    status: Taskboard.TaskStatus;
    priority: Taskboard.TaskPriority;
    /** The project this task belongs to */
    project_id?: string;
    /** Email of the person assigned to this task */
    assignee?: string;
    /** The date this task is due */
    due_date?: string;
    /** Labels attached to this task */
    tags?: string[];
    /** When the task was created */
    created_at: string;
    /** When the task was last updated */
    updated_at: string;
}
