// Code generated by Fern. DO NOT EDIT.

package projects

import (
	context "context"
	taskboard "github.com/taskboard/taskboard-go"
	core "github.com/taskboard/taskboard-go/core"
	internal "github.com/taskboard/taskboard-go/internal"
	option "github.com/taskboard/taskboard-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Returns all projects accessible to the authenticated user.
func (c *Client) ListProjects(
	ctx context.Context,
	opts ...option.RequestOption,
) ([]*taskboard.Project, error) {
	response, err := c.WithRawResponse.ListProjects(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Creates a new project.
func (c *Client) CreateProject(
	ctx context.Context,
	request *taskboard.CreateProjectRequest,
	opts ...option.RequestOption,
) (*taskboard.Project, error) {
	response, err := c.WithRawResponse.CreateProject(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns a single project by its ID.
func (c *Client) GetProject(
	ctx context.Context,
	request *taskboard.GetProjectRequest,
	opts ...option.RequestOption,
) (*taskboard.Project, error) {
	response, err := c.WithRawResponse.GetProject(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Permanently deletes a project and all its tasks.
func (c *Client) DeleteProject(
	ctx context.Context,
	request *taskboard.DeleteProjectRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.DeleteProject(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}
