// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Taskboard from "../../../index.js";

export declare namespace TasksClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Create and manage tasks
 */
export class TasksClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<TasksClient.Options>;

    constructor(options: TasksClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Returns a paginated list of tasks. Optionally filter by project, status, or priority.
     *
     * @param {Taskboard.ListTasksRequest} request
     * @param {TasksClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Taskboard.UnauthorizedError}
     *
     * @example
     *     await client.tasks.listTasks()
     */
    public listTasks(
        request: Taskboard.ListTasksRequest = {},
        requestOptions?: TasksClient.RequestOptions,
    ): core.HttpResponsePromise<Taskboard.TaskList> {
        return core.HttpResponsePromise.fromPromise(this.__listTasks(request, requestOptions));
    }

    private async __listTasks(
        request: Taskboard.ListTasksRequest = {},
        requestOptions?: TasksClient.RequestOptions,
    ): Promise<core.WithRawResponse<Taskboard.TaskList>> {
        const { project_id: projectId, status, priority, limit, offset } = request;
        const _queryParams: Record<string, unknown> = {
            project_id: projectId,
            status: status != null ? status : undefined,
            priority: priority != null ? priority : undefined,
            limit,
            offset,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TaskboardEnvironment.Production,
                "tasks",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Taskboard.TaskList, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Taskboard.UnauthorizedError(
                        _response.error.body as Taskboard.Error_,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TaskboardError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/tasks");
    }

    /**
     * Creates a new task and returns it.
     *
     * @param {Taskboard.CreateTaskRequest} request
     * @param {TasksClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Taskboard.BadRequestError}
     * @throws {@link Taskboard.UnauthorizedError}
     *
     * @example
     *     await client.tasks.createTask({
     *         title: "title"
     *     })
     */
    public createTask(
        request: Taskboard.CreateTaskRequest,
        requestOptions?: TasksClient.RequestOptions,
    ): core.HttpResponsePromise<Taskboard.Task> {
        return core.HttpResponsePromise.fromPromise(this.__createTask(request, requestOptions));
    }

    private async __createTask(
        request: Taskboard.CreateTaskRequest,
        requestOptions?: TasksClient.RequestOptions,
    ): Promise<core.WithRawResponse<Taskboard.Task>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TaskboardEnvironment.Production,
                "tasks",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Taskboard.Task, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Taskboard.BadRequestError(
                        _response.error.body as Taskboard.Error_,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Taskboard.UnauthorizedError(
                        _response.error.body as Taskboard.Error_,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TaskboardError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/tasks");
    }

    /**
     * Returns a single task by its ID.
     *
     * @param {Taskboard.GetTaskRequest} request
     * @param {TasksClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Taskboard.UnauthorizedError}
     * @throws {@link Taskboard.NotFoundError}
     *
     * @example
     *     await client.tasks.getTask({
     *         task_id: "task_id"
     *     })
     */
    public getTask(
        request: Taskboard.GetTaskRequest,
        requestOptions?: TasksClient.RequestOptions,
    ): core.HttpResponsePromise<Taskboard.Task> {
        return core.HttpResponsePromise.fromPromise(this.__getTask(request, requestOptions));
    }

    private async __getTask(
        request: Taskboard.GetTaskRequest,
        requestOptions?: TasksClient.RequestOptions,
    ): Promise<core.WithRawResponse<Taskboard.Task>> {
        const { task_id: taskId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TaskboardEnvironment.Production,
                `tasks/${core.url.encodePathParam(taskId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Taskboard.Task, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Taskboard.UnauthorizedError(
                        _response.error.body as Taskboard.Error_,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Taskboard.NotFoundError(_response.error.body as Taskboard.Error_, _response.rawResponse);
                default:
                    throw new errors.TaskboardError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/tasks/{task_id}");
    }

    /**
     * Permanently deletes a task.
     *
     * @param {Taskboard.DeleteTaskRequest} request
     * @param {TasksClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Taskboard.UnauthorizedError}
     * @throws {@link Taskboard.NotFoundError}
     *
     * @example
     *     await client.tasks.deleteTask({
     *         task_id: "task_id"
     *     })
     */
    public deleteTask(
        request: Taskboard.DeleteTaskRequest,
        requestOptions?: TasksClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__deleteTask(request, requestOptions));
    }

    private async __deleteTask(
        request: Taskboard.DeleteTaskRequest,
        requestOptions?: TasksClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { task_id: taskId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TaskboardEnvironment.Production,
                `tasks/${core.url.encodePathParam(taskId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Taskboard.UnauthorizedError(
                        _response.error.body as Taskboard.Error_,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Taskboard.NotFoundError(_response.error.body as Taskboard.Error_, _response.rawResponse);
                default:
                    throw new errors.TaskboardError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "DELETE", "/tasks/{task_id}");
    }

    /**
     * Updates an existing task. Only provided fields will be changed.
     *
     * @param {Taskboard.UpdateTaskRequest} request
     * @param {TasksClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Taskboard.BadRequestError}
     * @throws {@link Taskboard.UnauthorizedError}
     * @throws {@link Taskboard.NotFoundError}
     *
     * @example
     *     await client.tasks.updateTask({
     *         task_id: "task_id"
     *     })
     */
    public updateTask(
        request: Taskboard.UpdateTaskRequest,
        requestOptions?: TasksClient.RequestOptions,
    ): core.HttpResponsePromise<Taskboard.Task> {
        return core.HttpResponsePromise.fromPromise(this.__updateTask(request, requestOptions));
    }

    private async __updateTask(
        request: Taskboard.UpdateTaskRequest,
        requestOptions?: TasksClient.RequestOptions,
    ): Promise<core.WithRawResponse<Taskboard.Task>> {
        const { task_id: taskId, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TaskboardEnvironment.Production,
                `tasks/${core.url.encodePathParam(taskId)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Taskboard.Task, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Taskboard.BadRequestError(
                        _response.error.body as Taskboard.Error_,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Taskboard.UnauthorizedError(
                        _response.error.body as Taskboard.Error_,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Taskboard.NotFoundError(_response.error.body as Taskboard.Error_, _response.rawResponse);
                default:
                    throw new errors.TaskboardError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PATCH", "/tasks/{task_id}");
    }
}
