// Code generated by Fern. DO NOT EDIT.

package client

import (
	core "github.com/taskboard/taskboard-go/core"
	internal "github.com/taskboard/taskboard-go/internal"
	option "github.com/taskboard/taskboard-go/option"
	projects "github.com/taskboard/taskboard-go/projects"
	tasks "github.com/taskboard/taskboard-go/tasks"
)

type Client struct {
	Tasks    *tasks.Client
	Projects *projects.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		Tasks:    tasks.NewClient(options),
		Projects: projects.NewClient(options),
		options:  options,
		baseURL:  options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}
