// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         name: "name"
 *     }
 */
export interface CreateProjectRequest {
    /** Name of the project */
    name: string;
    /** A brief description of the project */
    description?: string;
}
