// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         project_id: "project_id"
 *     }
 */
export interface DeleteProjectRequest {
    /** The unique identifier of the project */
    project_id: string;
}
