// Code generated by Fern. DO NOT EDIT.

package tasks

import (
	context "context"
	taskboard "github.com/taskboard/taskboard-go"
	core "github.com/taskboard/taskboard-go/core"
	internal "github.com/taskboard/taskboard-go/internal"
	option "github.com/taskboard/taskboard-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Returns a paginated list of tasks. Optionally filter by project, status, or priority.
func (c *Client) ListTasks(
	ctx context.Context,
	request *taskboard.ListTasksRequest,
	opts ...option.RequestOption,
) (*taskboard.TaskList, error) {
	response, err := c.WithRawResponse.ListTasks(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Creates a new task and returns it.
func (c *Client) CreateTask(
	ctx context.Context,
	request *taskboard.CreateTaskRequest,
	opts ...option.RequestOption,
) (*taskboard.Task, error) {
	response, err := c.WithRawResponse.CreateTask(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns a single task by its ID.
func (c *Client) GetTask(
	ctx context.Context,
	request *taskboard.GetTaskRequest,
	opts ...option.RequestOption,
) (*taskboard.Task, error) {
	response, err := c.WithRawResponse.GetTask(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Permanently deletes a task.
func (c *Client) DeleteTask(
	ctx context.Context,
	request *taskboard.DeleteTaskRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.DeleteTask(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// Updates an existing task. Only provided fields will be changed.
func (c *Client) UpdateTask(
	ctx context.Context,
	request *taskboard.UpdateTaskRequest,
	opts ...option.RequestOption,
) (*taskboard.Task, error) {
	response, err := c.WithRawResponse.UpdateTask(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
