// This file was auto-generated by Fern from our API Definition.

import type * as Taskboard from "../../../../index.js";

/**
 * @example
 *     {
 *         title: "title"
 *     }
 */
export interface CreateTaskRequest {
    /** Short summary of the task */
    title: string;
    /** Detailed description of the task */
    description?: string;
    status?: Taskboard.TaskStatus;
    priority?: Taskboard.TaskPriority;
    /** The project to assign this task to */
    project_id?: string;
    /** Email of the person to assign */
    assignee?: string;
    /** The date this task is due */
    due_date?: string;
    /** Labels to attach to this task */
    tags?: string[];
}
