// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         task_id: "task_id"
 *     }
 */
export interface GetTaskRequest {
    /** The unique identifier of the task */
    task_id: string;
}
