// This file was auto-generated by Fern from our API Definition.

import type * as Taskboard from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface ListTasksRequest {
    /** Filter tasks by project ID */
    project_id?: string;
    /** Filter tasks by status */
    status?: Taskboard.TaskStatus;
    /** Filter tasks by priority */
    priority?: Taskboard.TaskPriority;
    /** Maximum number of tasks to return */
    limit?: number;
    /** Number of tasks to skip */
    offset?: number;
}
