// This file was auto-generated by Fern from our API Definition.

import type * as Taskboard from "../../../../index.js";

/**
 * @example
 *     {
 *         task_id: "task_id"
 *     }
 */
export interface UpdateTaskRequest {
    /** The unique identifier of the task */
    task_id: string;
    title?: string;
    description?: string;
    status?: Taskboard.TaskStatus;
    priority?: Taskboard.TaskPriority;
    project_id?: string;
    assignee?: string;
    due_date?: string;
    tags?: string[];
}
