// This file was auto-generated by Fern from our API Definition.

import { ProjectsClient } from "./api/resources/projects/client/Client.js";
import { TasksClient } from "./api/resources/tasks/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";

export declare namespace TaskboardClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class TaskboardClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<TaskboardClient.Options>;
    protected _tasks: TasksClient | undefined;
    protected _projects: ProjectsClient | undefined;

    constructor(options: TaskboardClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get tasks(): TasksClient {
        return (this._tasks ??= new TasksClient(this._options));
    }

    public get projects(): ProjectsClient {
        return (this._projects ??= new ProjectsClient(this._options));
    }
}
