// This file was auto-generated by Fern from our API Definition.

export const TaskboardEnvironment = {
    Production: "https://api.taskboard.dev",
} as const;

export type TaskboardEnvironment = typeof TaskboardEnvironment.Production;
