// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Taskboard from "../../../index.js";

export declare namespace ProjectsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Organize tasks into projects
 */
export class ProjectsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<ProjectsClient.Options>;

    constructor(options: ProjectsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Returns all projects accessible to the authenticated user.
     *
     * @param {ProjectsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Taskboard.UnauthorizedError}
     *
     * @example
     *     await client.projects.listProjects()
     */
    public listProjects(requestOptions?: ProjectsClient.RequestOptions): core.HttpResponsePromise<Taskboard.Project[]> {
        return core.HttpResponsePromise.fromPromise(this.__listProjects(requestOptions));
    }

    private async __listProjects(
        requestOptions?: ProjectsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Taskboard.Project[]>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TaskboardEnvironment.Production,
                "projects",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Taskboard.Project[], rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Taskboard.UnauthorizedError(
                        _response.error.body as Taskboard.Error_,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TaskboardError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/projects");
    }

    /**
     * Creates a new project.
     *
     * @param {Taskboard.CreateProjectRequest} request
     * @param {ProjectsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Taskboard.BadRequestError}
     * @throws {@link Taskboard.UnauthorizedError}
     *
     * @example
     *     await client.projects.createProject({
     *         name: "name"
     *     })
     */
    public createProject(
        request: Taskboard.CreateProjectRequest,
        requestOptions?: ProjectsClient.RequestOptions,
    ): core.HttpResponsePromise<Taskboard.Project> {
        return core.HttpResponsePromise.fromPromise(this.__createProject(request, requestOptions));
    }

    private async __createProject(
        request: Taskboard.CreateProjectRequest,
        requestOptions?: ProjectsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Taskboard.Project>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TaskboardEnvironment.Production,
                "projects",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Taskboard.Project, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Taskboard.BadRequestError(
                        _response.error.body as Taskboard.Error_,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Taskboard.UnauthorizedError(
                        _response.error.body as Taskboard.Error_,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TaskboardError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/projects");
    }

    /**
     * Returns a single project by its ID.
     *
     * @param {Taskboard.GetProjectRequest} request
     * @param {ProjectsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Taskboard.UnauthorizedError}
     * @throws {@link Taskboard.NotFoundError}
     *
     * @example
     *     await client.projects.getProject({
     *         project_id: "project_id"
     *     })
     */
    public getProject(
        request: Taskboard.GetProjectRequest,
        requestOptions?: ProjectsClient.RequestOptions,
    ): core.HttpResponsePromise<Taskboard.Project> {
        return core.HttpResponsePromise.fromPromise(this.__getProject(request, requestOptions));
    }

    private async __getProject(
        request: Taskboard.GetProjectRequest,
        requestOptions?: ProjectsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Taskboard.Project>> {
        const { project_id: projectId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TaskboardEnvironment.Production,
                `projects/${core.url.encodePathParam(projectId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Taskboard.Project, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Taskboard.UnauthorizedError(
                        _response.error.body as Taskboard.Error_,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Taskboard.NotFoundError(_response.error.body as Taskboard.Error_, _response.rawResponse);
                default:
                    throw new errors.TaskboardError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/projects/{project_id}");
    }

    /**
     * Permanently deletes a project and all its tasks.
     *
     * @param {Taskboard.DeleteProjectRequest} request
     * @param {ProjectsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Taskboard.UnauthorizedError}
     * @throws {@link Taskboard.NotFoundError}
     *
     * @example
     *     await client.projects.deleteProject({
     *         project_id: "project_id"
     *     })
     */
    public deleteProject(
        request: Taskboard.DeleteProjectRequest,
        requestOptions?: ProjectsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__deleteProject(request, requestOptions));
    }

    private async __deleteProject(
        request: Taskboard.DeleteProjectRequest,
        requestOptions?: ProjectsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { project_id: projectId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TaskboardEnvironment.Production,
                `projects/${core.url.encodePathParam(projectId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Taskboard.UnauthorizedError(
                        _response.error.body as Taskboard.Error_,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Taskboard.NotFoundError(_response.error.body as Taskboard.Error_, _response.rawResponse);
                default:
                    throw new errors.TaskboardError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "DELETE", "/projects/{project_id}");
    }
}
