// Code generated by Fern. DO NOT EDIT.

package taskboard

import (
	core "github.com/taskboard/taskboard-go/core"
	internal "github.com/taskboard/taskboard-go/internal"
)

var ErrorCodes internal.ErrorCodes = internal.ErrorCodes{
	401: func(apiError *core.APIError) error {
		return &UnauthorizedError{
			APIError: apiError,
		}
	},
	400: func(apiError *core.APIError) error {
		return &BadRequestError{
			APIError: apiError,
		}
	},
	404: func(apiError *core.APIError) error {
		return &NotFoundError{
			APIError: apiError,
		}
	},
}
