// Code generated by Fern. DO NOT EDIT.

package taskboard

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/taskboard/taskboard-go/internal"
	big "math/big"
	time "time"
)

var (
	createProjectRequestFieldName        = big.NewInt(1 << 0)
	createProjectRequestFieldDescription = big.NewInt(1 << 1)
)

type CreateProjectRequest struct {
	// Name of the project
	Name string `json:"name" url:"-"`
	// A brief description of the project
	Description *string `json:"description,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateProjectRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateProjectRequest) SetName(name string) {
	c.Name = name
	c.require(createProjectRequestFieldName)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateProjectRequest) SetDescription(description *string) {
	c.Description = description
	c.require(createProjectRequestFieldDescription)
}

var (
	deleteProjectRequestFieldProjectID = big.NewInt(1 << 0)
)

type DeleteProjectRequest struct {
	// The unique identifier of the project
	ProjectID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteProjectRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetProjectID sets the ProjectID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteProjectRequest) SetProjectID(projectID string) {
	d.ProjectID = projectID
	d.require(deleteProjectRequestFieldProjectID)
}

var (
	getProjectRequestFieldProjectID = big.NewInt(1 << 0)
)

type GetProjectRequest struct {
	// The unique identifier of the project
	ProjectID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetProjectRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetProjectID sets the ProjectID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetProjectRequest) SetProjectID(projectID string) {
	g.ProjectID = projectID
	g.require(getProjectRequestFieldProjectID)
}

var (
	projectFieldID          = big.NewInt(1 << 0)
	projectFieldName        = big.NewInt(1 << 1)
	projectFieldDescription = big.NewInt(1 << 2)
	projectFieldCreatedAt   = big.NewInt(1 << 3)
)

type Project struct {
	// Unique identifier for the project
	ID string `json:"id" url:"id"`
	// Name of the project
	Name string `json:"name" url:"name"`
	// A brief description of the project
	Description *string `json:"description,omitempty" url:"description,omitempty"`
	// When the project was created
	CreatedAt time.Time `json:"created_at" url:"created_at"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *Project) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *Project) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *Project) GetDescription() *string {
	if p == nil {
		return nil
	}
	return p.Description
}

func (p *Project) GetCreatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.CreatedAt
}

func (p *Project) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *Project) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *Project) SetID(id string) {
	p.ID = id
	p.require(projectFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *Project) SetName(name string) {
	p.Name = name
	p.require(projectFieldName)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *Project) SetDescription(description *string) {
	p.Description = description
	p.require(projectFieldDescription)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *Project) SetCreatedAt(createdAt time.Time) {
	p.CreatedAt = createdAt
	p.require(projectFieldCreatedAt)
}

func (p *Project) UnmarshalJSON(data []byte) error {
	type embed Project
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at"`
	}{
		embed: embed(*p),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*p = Project(unmarshaler.embed)
	p.CreatedAt = unmarshaler.CreatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *Project) MarshalJSON() ([]byte, error) {
	type embed Project
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at"`
	}{
		embed:     embed(*p),
		CreatedAt: internal.NewDateTime(p.CreatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *Project) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}
