// Code generated by Fern. DO NOT EDIT.

package taskboard

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/taskboard/taskboard-go/internal"
	big "math/big"
	time "time"
)

var (
	createTaskRequestFieldTitle       = big.NewInt(1 << 0)
	createTaskRequestFieldDescription = big.NewInt(1 << 1)
	createTaskRequestFieldStatus      = big.NewInt(1 << 2)
	createTaskRequestFieldPriority    = big.NewInt(1 << 3)
	createTaskRequestFieldProjectID   = big.NewInt(1 << 4)
	createTaskRequestFieldAssignee    = big.NewInt(1 << 5)
	createTaskRequestFieldDueDate     = big.NewInt(1 << 6)
	createTaskRequestFieldTags        = big.NewInt(1 << 7)
)

type CreateTaskRequest struct {
	// Short summary of the task
	Title string `json:"title" url:"-"`
	// Detailed description of the task
	Description *string       `json:"description,omitempty" url:"-"`
	Status      *TaskStatus   `json:"status,omitempty" url:"-"`
	Priority    *TaskPriority `json:"priority,omitempty" url:"-"`
	// The project to assign this task to
	ProjectID *string `json:"project_id,omitempty" url:"-"`
	// Email of the person to assign
	Assignee *string `json:"assignee,omitempty" url:"-"`
	// The date this task is due
	DueDate *time.Time `json:"due_date,omitempty" url:"-" format:"date"`
	// Labels to attach to this task
	Tags []string `json:"tags,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateTaskRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetTitle sets the Title field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateTaskRequest) SetTitle(title string) {
	c.Title = title
	c.require(createTaskRequestFieldTitle)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateTaskRequest) SetDescription(description *string) {
	c.Description = description
	c.require(createTaskRequestFieldDescription)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateTaskRequest) SetStatus(status *TaskStatus) {
	c.Status = status
	c.require(createTaskRequestFieldStatus)
}

// SetPriority sets the Priority field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateTaskRequest) SetPriority(priority *TaskPriority) {
	c.Priority = priority
	c.require(createTaskRequestFieldPriority)
}

// SetProjectID sets the ProjectID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateTaskRequest) SetProjectID(projectID *string) {
	c.ProjectID = projectID
	c.require(createTaskRequestFieldProjectID)
}

// SetAssignee sets the Assignee field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateTaskRequest) SetAssignee(assignee *string) {
	c.Assignee = assignee
	c.require(createTaskRequestFieldAssignee)
}

// SetDueDate sets the DueDate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateTaskRequest) SetDueDate(dueDate *time.Time) {
	c.DueDate = dueDate
	c.require(createTaskRequestFieldDueDate)
}

// SetTags sets the Tags field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateTaskRequest) SetTags(tags []string) {
	c.Tags = tags
	c.require(createTaskRequestFieldTags)
}

func (c *CreateTaskRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateTaskRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateTaskRequest(body)
	return nil
}

func (c *CreateTaskRequest) MarshalJSON() ([]byte, error) {
	type embed CreateTaskRequest
	var marshaler = struct {
		embed
		DueDate *internal.Date `json:"due_date,omitempty"`
	}{
		embed:   embed(*c),
		DueDate: internal.NewOptionalDate(c.DueDate),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	deleteTaskRequestFieldTaskID = big.NewInt(1 << 0)
)

type DeleteTaskRequest struct {
	// The unique identifier of the task
	TaskID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteTaskRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetTaskID sets the TaskID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteTaskRequest) SetTaskID(taskID string) {
	d.TaskID = taskID
	d.require(deleteTaskRequestFieldTaskID)
}

var (
	getTaskRequestFieldTaskID = big.NewInt(1 << 0)
)

type GetTaskRequest struct {
	// The unique identifier of the task
	TaskID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetTaskRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetTaskID sets the TaskID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetTaskRequest) SetTaskID(taskID string) {
	g.TaskID = taskID
	g.require(getTaskRequestFieldTaskID)
}

var (
	listTasksRequestFieldProjectID = big.NewInt(1 << 0)
	listTasksRequestFieldStatus    = big.NewInt(1 << 1)
	listTasksRequestFieldPriority  = big.NewInt(1 << 2)
	listTasksRequestFieldLimit     = big.NewInt(1 << 3)
	listTasksRequestFieldOffset    = big.NewInt(1 << 4)
)

type ListTasksRequest struct {
	// Filter tasks by project ID
	ProjectID *string `json:"-" url:"project_id,omitempty"`
	// Filter tasks by status
	Status *TaskStatus `json:"-" url:"status,omitempty"`
	// Filter tasks by priority
	Priority *TaskPriority `json:"-" url:"priority,omitempty"`
	// Maximum number of tasks to return
	Limit *int `json:"-" url:"limit,omitempty"`
	// Number of tasks to skip
	Offset *int `json:"-" url:"offset,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListTasksRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetProjectID sets the ProjectID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListTasksRequest) SetProjectID(projectID *string) {
	l.ProjectID = projectID
	l.require(listTasksRequestFieldProjectID)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListTasksRequest) SetStatus(status *TaskStatus) {
	l.Status = status
	l.require(listTasksRequestFieldStatus)
}

// SetPriority sets the Priority field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListTasksRequest) SetPriority(priority *TaskPriority) {
	l.Priority = priority
	l.require(listTasksRequestFieldPriority)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListTasksRequest) SetLimit(limit *int) {
	l.Limit = limit
	l.require(listTasksRequestFieldLimit)
}

// SetOffset sets the Offset field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListTasksRequest) SetOffset(offset *int) {
	l.Offset = offset
	l.require(listTasksRequestFieldOffset)
}

var (
	taskFieldID          = big.NewInt(1 << 0)
	taskFieldTitle       = big.NewInt(1 << 1)
	taskFieldDescription = big.NewInt(1 << 2)
	taskFieldStatus      = big.NewInt(1 << 3)
	taskFieldPriority    = big.NewInt(1 << 4)
	taskFieldProjectID   = big.NewInt(1 << 5)
	taskFieldAssignee    = big.NewInt(1 << 6)
	taskFieldDueDate     = big.NewInt(1 << 7)
	taskFieldTags        = big.NewInt(1 << 8)
	taskFieldCreatedAt   = big.NewInt(1 << 9)
	taskFieldUpdatedAt   = big.NewInt(1 << 10)
)

type Task struct {
	// Unique identifier for the task
	ID string `json:"id" url:"id"`
	// Short summary of the task
	Title string `json:"title" url:"title"`
	// Detailed description of the task
	Description *string      `json:"description,omitempty" url:"description,omitempty"`
	Status      TaskStatus   `json:"status" url:"status"`
	Priority    TaskPriority `json:"priority" url:"priority"`
	// The project this task belongs to
	ProjectID *string `json:"project_id,omitempty" url:"project_id,omitempty"`
	// Email of the person assigned to this task
	Assignee *string `json:"assignee,omitempty" url:"assignee,omitempty"`
	// The date this task is due
	DueDate *time.Time `json:"due_date,omitempty" url:"due_date,omitempty" format:"date"`
	// Labels attached to this task
	Tags []string `json:"tags,omitempty" url:"tags,omitempty"`
	// When the task was created
	CreatedAt time.Time `json:"created_at" url:"created_at"`
	// When the task was last updated
	UpdatedAt time.Time `json:"updated_at" url:"updated_at"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *Task) GetID() string {
	if t == nil {
		return ""
	}
	return t.ID
}

func (t *Task) GetTitle() string {
	if t == nil {
		return ""
	}
	return t.Title
}

func (t *Task) GetDescription() *string {
	if t == nil {
		return nil
	}
	return t.Description
}

func (t *Task) GetStatus() TaskStatus {
	if t == nil {
		return ""
	}
	return t.Status
}

func (t *Task) GetPriority() TaskPriority {
	if t == nil {
		return ""
	}
	return t.Priority
}

func (t *Task) GetProjectID() *string {
	if t == nil {
		return nil
	}
	return t.ProjectID
}

func (t *Task) GetAssignee() *string {
	if t == nil {
		return nil
	}
	return t.Assignee
}

func (t *Task) GetDueDate() *time.Time {
	if t == nil {
		return nil
	}
	return t.DueDate
}

func (t *Task) GetTags() []string {
	if t == nil {
		return nil
	}
	return t.Tags
}

func (t *Task) GetCreatedAt() time.Time {
	if t == nil {
		return time.Time{}
	}
	return t.CreatedAt
}

func (t *Task) GetUpdatedAt() time.Time {
	if t == nil {
		return time.Time{}
	}
	return t.UpdatedAt
}

func (t *Task) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *Task) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *Task) SetID(id string) {
	t.ID = id
	t.require(taskFieldID)
}

// SetTitle sets the Title field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *Task) SetTitle(title string) {
	t.Title = title
	t.require(taskFieldTitle)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *Task) SetDescription(description *string) {
	t.Description = description
	t.require(taskFieldDescription)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *Task) SetStatus(status TaskStatus) {
	t.Status = status
	t.require(taskFieldStatus)
}

// SetPriority sets the Priority field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *Task) SetPriority(priority TaskPriority) {
	t.Priority = priority
	t.require(taskFieldPriority)
}

// SetProjectID sets the ProjectID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *Task) SetProjectID(projectID *string) {
	t.ProjectID = projectID
	t.require(taskFieldProjectID)
}

// SetAssignee sets the Assignee field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *Task) SetAssignee(assignee *string) {
	t.Assignee = assignee
	t.require(taskFieldAssignee)
}

// SetDueDate sets the DueDate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *Task) SetDueDate(dueDate *time.Time) {
	t.DueDate = dueDate
	t.require(taskFieldDueDate)
}

// SetTags sets the Tags field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *Task) SetTags(tags []string) {
	t.Tags = tags
	t.require(taskFieldTags)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *Task) SetCreatedAt(createdAt time.Time) {
	t.CreatedAt = createdAt
	t.require(taskFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *Task) SetUpdatedAt(updatedAt time.Time) {
	t.UpdatedAt = updatedAt
	t.require(taskFieldUpdatedAt)
}

func (t *Task) UnmarshalJSON(data []byte) error {
	type embed Task
	var unmarshaler = struct {
		embed
		DueDate   *internal.Date     `json:"due_date,omitempty"`
		CreatedAt *internal.DateTime `json:"created_at"`
		UpdatedAt *internal.DateTime `json:"updated_at"`
	}{
		embed: embed(*t),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*t = Task(unmarshaler.embed)
	t.DueDate = unmarshaler.DueDate.TimePtr()
	t.CreatedAt = unmarshaler.CreatedAt.Time()
	t.UpdatedAt = unmarshaler.UpdatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *Task) MarshalJSON() ([]byte, error) {
	type embed Task
	var marshaler = struct {
		embed
		DueDate   *internal.Date     `json:"due_date,omitempty"`
		CreatedAt *internal.DateTime `json:"created_at"`
		UpdatedAt *internal.DateTime `json:"updated_at"`
	}{
		embed:     embed(*t),
		DueDate:   internal.NewOptionalDate(t.DueDate),
		CreatedAt: internal.NewDateTime(t.CreatedAt),
		UpdatedAt: internal.NewDateTime(t.UpdatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *Task) String() string {
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

var (
	taskListFieldData   = big.NewInt(1 << 0)
	taskListFieldTotal  = big.NewInt(1 << 1)
	taskListFieldLimit  = big.NewInt(1 << 2)
	taskListFieldOffset = big.NewInt(1 << 3)
)

type TaskList struct {
	Data []*Task `json:"data" url:"data"`
	// Total number of tasks matching the query
	Total  int  `json:"total" url:"total"`
	Limit  *int `json:"limit,omitempty" url:"limit,omitempty"`
	Offset *int `json:"offset,omitempty" url:"offset,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TaskList) GetData() []*Task {
	if t == nil {
		return nil
	}
	return t.Data
}

func (t *TaskList) GetTotal() int {
	if t == nil {
		return 0
	}
	return t.Total
}

func (t *TaskList) GetLimit() *int {
	if t == nil {
		return nil
	}
	return t.Limit
}

func (t *TaskList) GetOffset() *int {
	if t == nil {
		return nil
	}
	return t.Offset
}

func (t *TaskList) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *TaskList) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TaskList) SetData(data []*Task) {
	t.Data = data
	t.require(taskListFieldData)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TaskList) SetTotal(total int) {
	t.Total = total
	t.require(taskListFieldTotal)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TaskList) SetLimit(limit *int) {
	t.Limit = limit
	t.require(taskListFieldLimit)
}

// SetOffset sets the Offset field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TaskList) SetOffset(offset *int) {
	t.Offset = offset
	t.require(taskListFieldOffset)
}

func (t *TaskList) UnmarshalJSON(data []byte) error {
	type unmarshaler TaskList
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TaskList(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TaskList) MarshalJSON() ([]byte, error) {
	type embed TaskList
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TaskList) String() string {
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

// The priority level of a task
type TaskPriority string

const (
	TaskPriorityLow    TaskPriority = "low"
	TaskPriorityMedium TaskPriority = "medium"
	TaskPriorityHigh   TaskPriority = "high"
	TaskPriorityUrgent TaskPriority = "urgent"
)

func NewTaskPriorityFromString(s string) (TaskPriority, error) {
	switch s {
	case "low":
		return TaskPriorityLow, nil
	case "medium":
		return TaskPriorityMedium, nil
	case "high":
		return TaskPriorityHigh, nil
	case "urgent":
		return TaskPriorityUrgent, nil
	}
	var t TaskPriority
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (t TaskPriority) Ptr() *TaskPriority {
	return &t
}

// The current status of a task
type TaskStatus string

const (
	TaskStatusBacklog    TaskStatus = "backlog"
	TaskStatusTodo       TaskStatus = "todo"
	TaskStatusInProgress TaskStatus = "in_progress"
	TaskStatusDone       TaskStatus = "done"
	TaskStatusCancelled  TaskStatus = "cancelled"
)

func NewTaskStatusFromString(s string) (TaskStatus, error) {
	switch s {
	case "backlog":
		return TaskStatusBacklog, nil
	case "todo":
		return TaskStatusTodo, nil
	case "in_progress":
		return TaskStatusInProgress, nil
	case "done":
		return TaskStatusDone, nil
	case "cancelled":
		return TaskStatusCancelled, nil
	}
	var t TaskStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (t TaskStatus) Ptr() *TaskStatus {
	return &t
}

var (
	updateTaskRequestFieldTaskID      = big.NewInt(1 << 0)
	updateTaskRequestFieldTitle       = big.NewInt(1 << 1)
	updateTaskRequestFieldDescription = big.NewInt(1 << 2)
	updateTaskRequestFieldStatus      = big.NewInt(1 << 3)
	updateTaskRequestFieldPriority    = big.NewInt(1 << 4)
	updateTaskRequestFieldProjectID   = big.NewInt(1 << 5)
	updateTaskRequestFieldAssignee    = big.NewInt(1 << 6)
	updateTaskRequestFieldDueDate     = big.NewInt(1 << 7)
	updateTaskRequestFieldTags        = big.NewInt(1 << 8)
)

type UpdateTaskRequest struct {
	// The unique identifier of the task
	TaskID      string        `json:"-" url:"-"`
	Title       *string       `json:"title,omitempty" url:"-"`
	Description *string       `json:"description,omitempty" url:"-"`
	Status      *TaskStatus   `json:"status,omitempty" url:"-"`
	Priority    *TaskPriority `json:"priority,omitempty" url:"-"`
	ProjectID   *string       `json:"project_id,omitempty" url:"-"`
	Assignee    *string       `json:"assignee,omitempty" url:"-"`
	DueDate     *time.Time    `json:"due_date,omitempty" url:"-" format:"date"`
	Tags        []string      `json:"tags,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UpdateTaskRequest) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetTaskID sets the TaskID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateTaskRequest) SetTaskID(taskID string) {
	u.TaskID = taskID
	u.require(updateTaskRequestFieldTaskID)
}

// SetTitle sets the Title field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateTaskRequest) SetTitle(title *string) {
	u.Title = title
	u.require(updateTaskRequestFieldTitle)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateTaskRequest) SetDescription(description *string) {
	u.Description = description
	u.require(updateTaskRequestFieldDescription)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateTaskRequest) SetStatus(status *TaskStatus) {
	u.Status = status
	u.require(updateTaskRequestFieldStatus)
}

// SetPriority sets the Priority field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateTaskRequest) SetPriority(priority *TaskPriority) {
	u.Priority = priority
	u.require(updateTaskRequestFieldPriority)
}

// SetProjectID sets the ProjectID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateTaskRequest) SetProjectID(projectID *string) {
	u.ProjectID = projectID
	u.require(updateTaskRequestFieldProjectID)
}

// SetAssignee sets the Assignee field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateTaskRequest) SetAssignee(assignee *string) {
	u.Assignee = assignee
	u.require(updateTaskRequestFieldAssignee)
}

// SetDueDate sets the DueDate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateTaskRequest) SetDueDate(dueDate *time.Time) {
	u.DueDate = dueDate
	u.require(updateTaskRequestFieldDueDate)
}

// SetTags sets the Tags field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateTaskRequest) SetTags(tags []string) {
	u.Tags = tags
	u.require(updateTaskRequestFieldTags)
}

func (u *UpdateTaskRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateTaskRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*u = UpdateTaskRequest(body)
	return nil
}

func (u *UpdateTaskRequest) MarshalJSON() ([]byte, error) {
	type embed UpdateTaskRequest
	var marshaler = struct {
		embed
		DueDate *internal.Date `json:"due_date,omitempty"`
	}{
		embed:   embed(*u),
		DueDate: internal.NewOptionalDate(u.DueDate),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}
